### ISSUE TITLE
snap-lens-file-inserter?

### ISSUE THREAD

**Issue by devnbp** [ptrumpis/snap-lens-file-extractor#1]
Hello, I'm looking for pack/unpack solution for lens files, there are another repo [snapchat-lens-blender-io](https://github.com/cvirostek/snapchat-lens-blender-io/), it unpacks the same way as your script, but it seems it packs the files incorrectly, so it is not working in Snap Camera. For example: I unpack a file of size 150Kb, the size of the unpacked folder is 250Kb, then I pack that folder, but the size of the file is 145Kb, and then I unpack the 145Kb file, but the size of the unpacked folder is 250Kb (same as the first times), so I assume the problem is that the metadata for the packed file is not set correctly.
I found packing method [here](https://github.com/cvirostek/snapchat-lens-blender-io/blob/master/lns_tool.py#L42), any thoughts on what is wrong here?

**Comment by ptrumpis** [comment]
Nice, I didn't know about the project. I will study the code.

Are you triying to use the re-packed modified lenses in Snap Camera?
The size difference of the packed archive should not matter at all. Don't worry about that.
It's determined by the compression ratio of the archive.
The compression can vary as long as the archive itself is valid similar to a zip archive.

Snap Camera desktop application uses a signature check to verify the origin of the lens archive.
On mobile devices you would have to jailbreak your device as stated by the repo.

> Retrieving a lense's LNS file requires a jailbroken iOS device or a rooted Android device. On iOS, LNS files can be found in /var/mobile/Containers/Data/Application/<id>/Library/Caches/Lenses. I don't have a rootable Android device, so I'm not sure where they would be located on Android.

On the desktop application you would have to remove/patch/crack the signature check.
I created these patches for the latest Windows and Mac OS versions of Snap Camera.

https://github.com/ptrumpis/snap-camera-signature-patch

With the signature check removed, the repacked lens should work.
But I never tested the lens modification process myself.

**Comment by devnbp** [comment]
I tried the repacked lens file with Snap Camera Signature Patch and it still doesn't work, when I replaced the original file with the repacked file and then applied the mask in Snap Camera (you also need reboot Snap Camera after replacing), none of the mask filters were applied to the camera output, there is no error, the app doesn't crash, just nothing happens.
![image](https://user-images.githubusercontent.com/46827723/236643084-4ba2c6e3-1cfa-45c4-b1a6-cc727f8b2e64.png)
This is what the original and repacked file look like, about 5 kb always disappear even when the original file size is ~100kb, that is why I thought the problem is that the metadata for the packed file is not set correctly by [write_lns method](https://github.com/cvirostek/snapchat-lens-blender-io/blob/master/lns_tool.py#L42)

**Comment by ptrumpis** [comment]
Did you check your log file?

`%USERPROFILE%\AppData\Local\Snap\Snap Camera\Log.txt`

**Comment by devnbp** [comment]
[Log.txt](https://github.com/ptrumpis/snap-lens-file-extractor/files/11413275/Log.txt)
```
Core: CORE: using complex effect with id lns://C:/Users/admin/AppData/Local/Snap/Snap Camera/cache/lenses/47392130875/lens.lns@@
Core: [LS::Graphics::Context] this - 0000007D48BFB8D0, glContext - 0000000000030001, glContextMode - 2
Core: [SGRenderer] Experiment value: 0
Core: bindScript executed
Core: [engine] engineComplexEffect started loading lens with id 47392130875
Core: [engine] The lens under development mode is OFF
Core: [OpenGL] contextsMap doesn't contain eglContext 0000000000030001
Core: [LS::Graphics::~Context] this - 0000007D48BFB8D0, glContext - 0000000000030001, glContextMode - 2
Core: [LS::Graphics::Context] this - 0000007D48BFB650, glContext - 0000000000030001, glContextMode - 2
Core: [engine] engine exception while processing lens with id 47392130875
Core: [OpenGL] contextsMap doesn't contain eglContext 0000000000030001
Core: [LS::Graphics::~Context] this - 0000007D48BFB650, glContext - 0000000000030001, glContextMode - 2
"Lens not loaded exception: Unable to open file for texture loading lns://C:/Users/admin/AppData/Local/Snap/Snap Camera/cache/lenses/47392130875/lens.lns@@/Files/File5/dog_down_v02-0.png"
```

**Comment by ptrumpis** [comment]
> /Files/File5/dog_down_v02-0.png

Well did you modify this file in anyway?
Seems to be unreadable for some reason

**Comment by devnbp** [comment]
No, I just unpacked and packed, I haven't made any changes to the files

**Comment by ptrumpis** [comment]
Well the file seems to be the reason for the failure.

I will provide a lens repacker in the near future.
Right now the public interest for such a feature doesn't seem high.

**Comment by ghalta22** [comment]
I was able to get the linked packing script working, however it has a bug when run under windows (discovered by comparing headers in a hex editor). The file paths that are written end up containing a mix of forward and backslashes, which confuses things and leads to those errors.

Quick fix is to change [this line](https://github.com/cvirostek/snapchat-lens-blender-io/blob/master/lns_tool.py#L37) to
`lns_path = full_path[len(real_path):].replace(os.sep, '/')`

**Comment by devnbp** [comment]
It works! Thank you, now I will try to figure out how to disable some filters on the mask

**Comment by IZeeLikeEyeZee** [comment]
Was importing lns files working for you? I keep getting this error whenever I try..

```
Traceback (most recent call last):
  File "C:\Users\IZee\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\snapchat_lens\blender\__init__.py", line 79, in execute
    imp.do_import()
  File "C:\Users\IZee\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\snapchat_lens\blender\lns_imp.py", line 11, in do_import
    files = parser.parse()
  File "C:\Users\IZee\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\snapchat_lens\common\parser\lns_parser.py", line 26, in parse
    dctx = zstd.ZstdDecompressor()
AttributeError: module 'zstd' has no attribute 'ZstdDecompressor'. Did you mean: 'ZSTD_compress'?
```

**Comment by ptrumpis** [comment]
There is now a new tool available that might be helpful [Snap Lens Tool](https://github.com/ptrumpis/snap-lens-tool).
