### ISSUE TITLE
Extractor goal

### ISSUE THREAD

**Issue by skyler14** [ptrumpis/snap-lens-file-extractor#4]
I want to understand where this project is going, is it fair to that your goal is to be able to extract the lens and actually run it on streams in a web browser via WebAssembly, or just an import export utility? Is the extracted content in a file format which it can be used in a program in similar to data like BFM.mat and the family of libraries built around that

**Comment by ptrumpis** [comment]
It is supposed to be a re-packing utility.
So you can extract and modify the file contents, which can be:
- Images (.jpg, .png ...)
- OpenGL Shader (.glsl)
- JavaScript (.js)
- Deep Neural Network Modul (.dnn)
- And other resources

Possible use cases after unpacking:
- Just taking a look out of curiosity
- Modify these files and re-pack them to customize lenses
- Loading them in another application (Blender for example)

The ultimate goal which is NOT scope of this repository...
... would be to build a custom face tracking application that is able to understand and load the various face filters.

**Comment by skyler14** [comment]
Gotcha, is there anything missing from the lns extraction to fully reload/import a lens to modify back into lens studio? I was trying to see if I could reimport an lns in lenstudio earlier so this sounds quite handy.

**Comment by ptrumpis** [comment]
I don't think it's possible to import the extracted files directly to Lens Studio without a lot of manual editing since the file structure is different. But I never tried it myself.

**Comment by skyler14** [comment]
what are all the types of file i might come across, ill update you on whats
possible if you can provide me a bit of info to read up on

**Comment by ptrumpis** [comment]
There is now a new tool available that might be helpful [Snap Lens Tool](https://github.com/ptrumpis/snap-lens-tool).
